name: Release

on:
    workflow_dispatch:

jobs:
    release:
        permissions:
            contents: write
            issues: write
            pull-requests: write

        name: Release
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v3
              with:
                  fetch-depth: 0

            - name: Setup Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: "lts/*"
                  registry-url: https://registry.npmjs.org

            - name: Install dependencies
              run: npm ci

            - name: Format code
              run: npm run format

            - name: Config
              run: npm run config

            - name: Build
              run: npm run build

            - name: Lint code
              run: npm run lint

            - name: Format code
              run: npm run format

            - name: Release
              run: npm run semantic-release
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
